# Welcome to Jekyll!

# Site Settings
title: Sunbochen's Website
name: Sunbochen Tang
email: your-email@example.com
include: ["_pages"]

# Theme Settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "default" etc.

# Production-specific settings
url: "https://tangsun.github.io"
repository: "tangsun/tangsun.github.io"
# baseurl remains empty
baseurl: ""

# Site Author
author:
  name             : "Sunbochen Tang"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Ph.D. Candidate in Autonomous Systems"
  location         : "Cambridge, MA"
  links:
    - label: "tangsun[at]mit[dot]edu"
      icon: "fas fa-fw fa-envelope-square"
      url: ""
    - label: "Google Scholar"
      icon: "fab fa-google-scholar"
      url: "https://scholar.google.com/citations?user=7xtBYY8AAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sunbochen-tang/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Tangsun"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true